# Generated by Django 4.1.13 on 2025-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Prof', 'Professeur'), ('Etudiant', 'Étudiant'), ('Admin', 'Administrateur')], default='Etudiant', max_length=20),
        ),
    ]
