# Generated by Django 4.2 on 2025-04-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='mention',
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(),
        ),
    ]
