# Generated by Django 4.2 on 2025-04-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0004_rename_note_note_valeur_note_remarque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='valeur',
            new_name='note',
        ),
    ]
